package jdk

import (
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"sync"

	"barista/internal/output"
)

// distros.json is generated by scripts/gen-distros.py; it pins stable
// (non-expiring) download URLs so installs and `jdk available` need no
// API queries for these distros.

//go:embed distros.json
var distrosJSON []byte

type embeddedAsset struct {
	URL    string `json:"url"`
	SHA256 string `json:"sha256,omitempty"`
}

type embeddedRelease struct {
	Major   int                      `json:"major"`
	Version string                   `json:"version"`
	LTS     bool                     `json:"lts"`
	Assets  map[string]embeddedAsset `json:"assets"`
}

type distrosFile struct {
	GeneratedAt string                       `json:"generatedAt"`
	Distros     map[string][]embeddedRelease `json:"distros"`
}

var loadEmbedded = sync.OnceValues(func() (distrosFile, error) {
	var f distrosFile
	if err := json.Unmarshal(distrosJSON, &f); err != nil {
		return f, err
	}
	return f, nil
})

type embeddedProvider struct{ distro string }

func (p embeddedProvider) releases() ([]embeddedRelease, error) {
	f, err := loadEmbedded()
	if err != nil {
		return nil, fmt.Errorf("distros.json: %v", err)
	}
	releases := f.Distros[p.distro]
	if len(releases) == 0 {
		return nil, fmt.Errorf("distros.json: no data for distro %q (regenerate with scripts/gen-distros.py)", p.distro)
	}
	return releases, nil
}

func (p embeddedProvider) ArchiveURL(major int, goos, goarch string) (string, error) {
	releases, err := p.releases()
	if err != nil {
		return "", err
	}
	for _, r := range releases {
		if r.Major != major {
			continue
		}
		asset, ok := r.Assets[goos+"/"+goarch]
		if !ok {
			return "", fmt.Errorf("%s %d: no build for %s/%s", p.distro, major, goos, goarch)
		}
		return asset.URL, nil
	}
	majors := make([]int, len(releases))
	for i, r := range releases {
		majors[i] = r.Major
	}
	return "", fmt.Errorf("%s: unsupported major %d (supported: %v)", p.distro, major, majors)
}

func (p embeddedProvider) Available(context.Context) ([]AvailableRelease, *output.ErrInfo) {
	releases, err := p.releases()
	if err != nil {
		return nil, &output.ErrInfo{Code: output.CodeJDKAvailableFailed, Message: err.Error()}
	}
	sorted := make([]embeddedRelease, len(releases))
	copy(sorted, releases)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Major < sorted[j].Major })
	latest := 0
	for _, r := range sorted {
		if r.LTS && r.Major > latest {
			latest = r.Major
		}
	}
	out := make([]AvailableRelease, len(sorted))
	for i, r := range sorted {
		out[i] = AvailableRelease{Major: r.Major, Version: r.Version, LTS: r.LTS, Latest: r.Major == latest}
	}
	return out, nil
}

// ChecksumProvider is implemented by providers that pin a sha256 for each
// archive (embedded data), letting install verify downloads without a
// runtime metadata call.
type ChecksumProvider interface {
	ExpectedSHA256(major int, goos, goarch string) (string, bool)
}

func (p embeddedProvider) ExpectedSHA256(major int, goos, goarch string) (string, bool) {
	releases, err := p.releases()
	if err != nil {
		return "", false
	}
	for _, r := range releases {
		if r.Major != major {
			continue
		}
		asset, ok := r.Assets[goos+"/"+goarch]
		if !ok || asset.SHA256 == "" {
			return "", false
		}
		return asset.SHA256, true
	}
	return "", false
}

// VerifySHA256 checks the file's sha256 against the hex-encoded want.
func VerifySHA256(path, want string) *output.ErrInfo {
	f, err := os.Open(path)
	if err != nil {
		return &output.ErrInfo{Code: output.CodeJDKDownloadFailed, Message: err.Error()}
	}
	defer func() { _ = f.Close() }()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return &output.ErrInfo{Code: output.CodeJDKDownloadFailed, Message: err.Error()}
	}
	got := hex.EncodeToString(h.Sum(nil))
	if !strings.EqualFold(got, want) {
		return &output.ErrInfo{
			Code:    output.CodeJDKChecksumMismatch,
			Message: fmt.Sprintf("sha256 mismatch: got %s, want %s", got, want),
			Hint:    "the download may be corrupted; try again",
		}
	}
	return nil
}
